huh:
  encore:
    entries:
      - { name: contao-watchlist-bundle, requiresCss: false, file: "vendor/heimrichhannot/contao-watchlist-bundle/src/Resources/assets/js/contao-watchlist-bundle.js" }
    legacy:
      js:
        - 'contao-watchlist-bundle'