huh_encore:
  js_entries:
    - { name: contao-watchlist-bundle, file: vendor/heimrichhannot/contao-watchlist-bundle/src/Resources/assets/js/contao-watchlist-bundle-init.js}
  unset_global_keys:
    js:
      - contao-watchlist-bundle
