huh:
    list:
        lists:
          - { name: watchlist_downloadlist, class: HeimrichHannot\WatchlistBundle\Lists\WatchlistDownloadList }
        items:
          - { name: watchlist-default, class: HeimrichHannot\WatchlistBundle\ListItem\WatchlistListItem }
        templates:
            item:
              - { name: watchlist-list-item, template: "@HeimrichHannotContaoWatchlist/list_item_watchlist.html.twig" }
              - { name: watchlist-downloadlist-item, template: "@HeimrichHannotContaoWatchlist/list_item_watchlist_download.html.twig" }