services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false
    bind:
      $rootDir: '%kernel.project_dir%'

  HeimrichHannot\WatchlistBundle\Controller\WatchlistActionController: ~