services:
  _defaults:
    autowire: true
    public: true

  huh.watchlist.data_container.module_container:
    class: HeimrichHannot\WatchlistBundle\DataContainer\ModuleContainer
  huh.watchlist.data_container.watchlist_config:
    class: HeimrichHannot\WatchlistBundle\DataContainer\WatchlistConfigContainer