services:
  _defaults:
    autowire: true
    public: true

  HeimrichHannot\WatchlistBundle\DataContainer\ModuleContainer: ~
  huh.watchlist.data_container.module_container: '@HeimrichHannot\WatchlistBundle\DataContainer\ModuleContainer'

  HeimrichHannot\WatchlistBundle\DataContainer\WatchlistConfigContainer: ~
  huh.watchlist.data_container.watchlist_config: '@HeimrichHannot\WatchlistBundle\DataContainer\WatchlistConfigContainer'