services:
  _defaults:
    public: true

  huh.watchlist.ajax_manager:
    class: HeimrichHannot\WatchlistBundle\Manager\AjaxManager
    arguments:
      - "@service_container"
      - "@huh.watchlist.template_manager"
      - "@huh.watchlist.action_manager"
      - "@huh.watchlist.watchlist_manager"

  huh.watchlist.watchlist_manager:
    class: HeimrichHannot\WatchlistBundle\Manager\WatchlistManager
    arguments:
      - "@contao.framework"
      - "@huh.watchlist.action_manager"
      - "@translator"

  huh.watchlist.watchlist_item_manager:
    class: HeimrichHannot\WatchlistBundle\Manager\WatchlistItemManager
    arguments:
      - "@contao.framework"
      - "@huh.utils.model"
  huh.watchlist.action_manager:
      class: HeimrichHannot\WatchlistBundle\Manager\WatchlistActionManager
      arguments:
        - "@contao.framework"
        - "@translator"
  huh.watchlist.template_manager:
    class: HeimrichHannot\WatchlistBundle\Model\WatchlistTemplateManager
    arguments:
      - "@service_container"
      - "@translator"

  huh.watchlist.choice.download_file:
    class: HeimrichHannot\WatchlistBundle\Choice\DownloadItemFileChoice
    autowire: true
  huh.watchlist.choice.download_entity:
    class: HeimrichHannot\WatchlistBundle\Choice\DownloadItemEntityChoice
    autowire: true
  huh.watchlist.choice.watchlist_file:
    class: HeimrichHannot\WatchlistBundle\Choice\WatchlistItemFileChoice
    autowire: true
  huh.watchlist.choice.watchlist_entity:
    class: HeimrichHannot\WatchlistBundle\Choice\WatchlistItemEntityChoice
    autowire: true
  huh.watchlist.choice.watchlist_label:
    class: HeimrichHannot\WatchlistBundle\Choice\WatchlistLabelChoice
    autowire: true
  huh.watchlist.choice.watchlist_window_template:
    class: HeimrichHannot\WatchlistBundle\Choice\WatchlistWindowTemplateChoice
    autowire: true

  huh.watchlist.data_container.callback_container:
      class: HeimrichHannot\WatchlistBundle\DataContainer\CallbackContainer