services:
  huh.watchlist.ajax_manager:
    class: HeimrichHannot\WatchlistBundle\Manager\AjaxManager
    arguments:
      - "@contao.framework"
      - "@huh.watchlist.template_manager"
      - "@huh.watchlist.action_manager"
      - "@huh.watchlist.watchlist_manager"
  huh.watchlist.watchlist_manager:
    class: HeimrichHannot\WatchlistBundle\Manager\WatchlistManager
    arguments:
      - "@contao.framework"
      - "@huh.watchlist.action_manager"
  huh.watchlist.watchlist_item_manager:
    class: HeimrichHannot\WatchlistBundle\Manager\WatchlistItemManager
    arguments:
      - "@contao.framework"
      - "@huh.utils.model"
  huh.watchlist.action_manager:
      class: HeimrichHannot\WatchlistBundle\Manager\WatchlistActionManager
      arguments:
        - "@contao.framework"
  huh.watchlist.template_manager:
    class: HeimrichHannot\WatchlistBundle\Model\WatchlistTemplateManager
    arguments:
      - "@contao.framework"
  huh.watchlist.download_item_file:
    class: HeimrichHannot\WatchlistBundle\Item\DownloadItemFile
  huh.watchlist.download_item_entity:
    class: HeimrichHannot\WatchlistBundle\Item\DownloadItemEntity
  huh.watchlist.watchlist_item_file:
      class: HeimrichHannot\WatchlistBundle\Item\WatchlistItemFile
  huh.watchlist.watchlist_item_entity:
    class: HeimrichHannot\WatchlistBundle\Item\WatchlistItemEntity
  huh.watchlist.choice.download_file:
    class: HeimrichHannot\WatchlistBundle\Choice\DownloadItemFileChoice
    arguments:
      - "@contao.framework"
  huh.watchlist.choice.download_entity:
    class: HeimrichHannot\WatchlistBundle\Choice\DownloadItemEntityChoice
    arguments:
      - "@contao.framework"
  huh.watchlist.choice.watchlist_file:
    class: HeimrichHannot\WatchlistBundle\Choice\WatchlistItemFileChoice
    arguments:
      - "@contao.framework"
  huh.watchlist.choice.watchlist_entity:
    class: HeimrichHannot\WatchlistBundle\Choice\WatchlistItemEntityChoice
    arguments:
      - "@contao.framework"
  huh.watchlist.data_container.module_container:
      class: HeimrichHannot\WatchlistBundle\DataContainer\ModuleContainer
  huh.watchlist.event_listener.watchlist_download_listener:
    class: HeimrichHannot\VmdBundle\EventListener\WatchlistEventListener