services:
  _defaults:
    public: true
    autowire: true

  HeimrichHannot\WatchlistBundle\:
    resource: '../../{Controller,DataContainer,EventListener,Migration,Util}/*'

  HeimrichHannot\WatchlistBundle\Migration\:
    resource: '../../Migration/*'
    tags:
      - { name: contao.migration }
